steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "asia-southeast1-docker.pkg.dev/heymax-kelvin-analytics/dbt-images/dbt-runner",
        "./dbt-docker-repo"
      ]

  - name: asia-southeast1-docker.pkg.dev/heymax-kelvin-analytics/dbt-images/dbt-runner
    entrypoint: bash
    args:
      - -c
      - |
        mkdir -p /builder/home/.dbt
        cat > /builder/home/.dbt/profiles.yml <<EOF
        dbt_bigquery_analytics:
          target: dev
          outputs:
            dev:
              type: bigquery
              method: oauth
              project: heymax-kelvin-analytics
              dataset: heymax_analytics
              location: US
              threads: 4
        EOF
        cd dbt_bigquery_analytics
        dbt deps
        dbt run --profiles-dir /builder/home/.dbt

timeout: 1200s

options:
  logging: CLOUD_LOGGING_ONLY